const sources = ['wowhead'];

const trinket = ({ id, itemId, name, category, instance, encounter, sourceType, icon, type, focus = 'universal' }) => ({
  id,
  itemId,
  name,
  category,
  origin: instance,
  drop: {
    encounter,
    instance,
    sourceType: sourceType || (category === 'raid' ? 'Raid' : 'Mythic+'),
  },
  icon,
  type,
  focus,
  sources,
});

export const rankingItems = [
  trinket({ id: 'soulcoiler-vessel', itemId: 270162, name: 'Soulcoiler Ritual Vessel', category: 'raid', instance: 'The Venomous Abyss', encounter: "Nek'zali the Soulcoiler", icon: 'inv_121_trinket_raid_ulatek_ritualvessel', type: 'on-use', focus: 'healer' }),
  trinket({ id: 'keepers-core', itemId: 270165, name: "Keeper's Seething Core", category: 'raid', instance: 'The Venomous Abyss', encounter: 'Entombed Sentinels', icon: 'inv_121_trinket_raid_ulatek_golemhearts_green', type: 'passive', focus: 'tank' }),
  trinket({ id: 'first-mates-shellward', itemId: 270160, name: "First Mate's Shellward", category: 'raid', instance: 'The Venomous Abyss', encounter: 'The Lost Explorers', icon: 'inv_cape_special_turtleshell_c_02', type: 'on-use', focus: 'tank' }),
  trinket({ id: 'gebbo', itemId: 270164, name: "Gebbo's Bottomless Bag", category: 'raid', instance: 'The Venomous Abyss', encounter: 'The Lost Explorers', icon: 'inv_10_tailoring_bag1_color2', type: 'passive' }),
  trinket({ id: 'vashnik-rancor', itemId: 270166, name: "Vashnik's Sanguine Rancor", category: 'raid', instance: 'The Venomous Abyss', encounter: 'Vashnik the Malignant', icon: 'inv_11_0_raid_gruesomesyringe_blue', type: 'passive' }),
  trinket({ id: 'fang-umbral-malignance', itemId: 270161, name: 'Fang of Umbral Malignance', category: 'raid', instance: 'The Venomous Abyss', encounter: 'Vashnik the Malignant', icon: 'inv_121_trinket_raid_ulatek_fang_purple', type: 'passive' }),
  trinket({ id: 'sszorak-ferocity', itemId: 270163, name: "Sszorak's Ferocity", category: 'raid', instance: 'The Venomous Abyss', encounter: 'Sszorak', icon: 'inv_121_trinket_raid_ulatek_ulatekclaw', type: 'passive' }),
  trinket({ id: 'howling-nexus-idol', itemId: 270174, name: 'Idol of the Howling Nexus', category: 'raid', instance: 'The Venomous Abyss', encounter: 'Sszorak', icon: 'inv_jewelcrafting_jadeserpent', type: 'passive' }),
  trinket({ id: 'preternatural-antivenom', itemId: 270171, name: 'Preternatural Antivenom', category: 'raid', instance: 'The Venomous Abyss', encounter: 'The Twin Fangs', icon: 'inv_11_0_dungeon_tentaclevial_green', type: 'passive', focus: 'healer' }),
  trinket({ id: 'vexhul-gland', itemId: 270170, name: "Vexhul's Everflowing Gland", category: 'raid', instance: 'The Venomous Abyss', encounter: 'The Twin Fangs', icon: 'inv_11_0_misc_organmass_color3', type: 'on-use' }),
  trinket({ id: 'hex-lord-idol', itemId: 270169, name: "Hex Lord's Dooming Idol", category: 'raid', instance: 'The Venomous Abyss', encounter: 'The Coiled Altar', icon: 'inv_archaeology_orcclans_crackedidol', type: 'on-use' }),
  trinket({ id: 'zuljin-technique', itemId: 270173, name: "Zul'jin's Guillotine Technique", category: 'raid', instance: 'The Venomous Abyss', encounter: 'The Coiled Altar', icon: 'inv_121_trinket_raid_ulatek_trolltablet', type: 'passive' }),
  trinket({ id: 'font-venomous-rage', itemId: 270168, name: 'Font of Venomous Rage', category: 'raid', instance: 'The Venomous Abyss', encounter: "Ula'tek", icon: 'inv_10_dungeonjewelry_dragon_trinket_3djardintrophy_green', type: 'on-use' }),
  trinket({ id: 'voracious-heart', itemId: 270175, name: "Voracious Heart of Ula'tek", category: 'raid', instance: 'The Venomous Abyss', encounter: "Ula'tek", icon: 'inv_121_trinket_raid_ulatek_heart', type: 'on-use' }),
  trinket({ id: 'wavecallers-seastone', itemId: 270167, name: "Wavecaller's Seastone", category: 'raid', instance: 'The Tidebound Grotto', encounter: 'Nymrissa Wavecaller', sourceType: 'Lair', icon: 'inv_tradeskillitem_sorcererswater', type: 'passive', focus: 'intellect' }),

  trinket({ id: 'coiled-fangstone', itemId: 273795, name: 'Coiled Fangstone', category: 'mythic-plus', instance: 'Altar of Fangs', encounter: "Rav'i", icon: 'inv_121_trinket_dungeon_ulatek_fangstone', type: 'on-use', focus: 'strength' }),
  trinket({ id: 'vial', itemId: 273796, name: 'Vile Vial of Volatile Venom', category: 'mythic-plus', instance: 'Altar of Fangs', encounter: "Rav'i", icon: 'inv_121_trinket_dungeon_ulatek_vile', type: 'on-use' }),
  trinket({ id: 'writhing-serpents', itemId: 273794, name: 'Knot of Writhing Serpents', category: 'mythic-plus', instance: 'Altar of Fangs', encounter: 'The Writhing Coil', icon: 'inv_121_trinket_dungeon_ulatek_writhe', type: 'passive', focus: 'intellect' }),
  trinket({ id: 'amani-war-banner', itemId: 273797, name: 'Tattered Amani War Banner', category: 'mythic-plus', instance: 'Altar of Fangs', encounter: "Zul'jan", icon: 'inv_121_trinket_dungeon_ulatek_banner', type: 'on-use' }),
  trinket({ id: 'manaheart-flame', itemId: 250243, name: "Manaheart's Binding Flame", category: 'mythic-plus', instance: 'Murder Row', encounter: 'Kystia Manaheart', icon: 'inv_ember_fel', type: 'on-use', focus: 'tank' }),
  trinket({ id: 'flask', itemId: 250215, name: "Freightrunner's Flask", category: 'mythic-plus', instance: 'Murder Row', encounter: 'Zaen Bladesorrow', icon: 'inv_alchemy_90_flask_red', type: 'on-use' }),
  trinket({ id: 'bellowstone', itemId: 250228, name: 'Resonant Bellowstone', category: 'mythic-plus', instance: 'Murder Row', encounter: 'Xathuux the Annihilator', icon: 'inv_alchemy_90_stone_green', type: 'passive' }),
  trinket({ id: 'felheart-crystal', itemId: 250255, name: 'Unstable Felheart Crystal', category: 'mythic-plus', instance: 'Murder Row', encounter: 'Lithiel Cinderfury', icon: 'tooltip_crystallizedfel', type: 'on-use', focus: 'healer' }),
  trinket({ id: 'radiant-hope', itemId: 250254, name: 'Seed of Radiant Hope', category: 'mythic-plus', instance: 'The Blinding Vale', encounter: 'Meittik', icon: 'inv12_jewelrytrinkets_dungeon_seedofradianthope', type: 'on-use', focus: 'healer' }),
  trinket({ id: 'devouring-wild', itemId: 250238, name: 'Seed of the Devouring Wild', category: 'mythic-plus', instance: 'The Blinding Vale', encounter: 'Ikuzz the Light Hunter', icon: 'inv12_jewelrytrinkets_dungeon_seedofthedevouringwild', type: 'on-use' }),
  trinket({ id: 'lightspire-core', itemId: 250214, name: 'Lightspire Core', category: 'mythic-plus', instance: 'The Blinding Vale', encounter: 'Lightwarden Ruia', icon: 'inv_enchant_essenceastrallarge', type: 'passive' }),
  trinket({ id: 'dawnroot-sapling', itemId: 250259, name: 'Sapling of the Dawnroot', category: 'mythic-plus', instance: 'The Blinding Vale', encounter: 'Ziekket', icon: 'inv_misc_herb_nightmarevine', type: 'passive' }),
  trinket({ id: 'void-mandate', itemId: 250225, name: 'Void Execution Mandate', category: 'mythic-plus', instance: 'Voidscar Arena', encounter: "Taz'Rah", icon: 'inv_inscription_80_warscroll_intellect', type: 'on-use' }),
  trinket({ id: 'swarm-tumor', itemId: 250245, name: 'Tumor of the Swarm', category: 'mythic-plus', instance: 'Voidscar Arena', encounter: 'Atroxus', icon: 'ability_pet_baneling', type: 'passive', focus: 'tank' }),
  trinket({ id: 'sigil', itemId: 250224, name: "Mindpiercer's Sigil", category: 'mythic-plus', instance: 'Voidscar Arena', encounter: 'Charonus', icon: 'inv_icon_shadowcouncilorb_purple', type: 'passive', focus: 'intellect' }),
  trinket({ id: 'mycolic-medicine', itemId: 250248, name: 'Mycolic Medicine', category: 'mythic-plus', instance: 'Den of Nalorakk', encounter: 'The Hoardmonger', icon: 'inv_misc_starspecklemushroom', type: 'passive', focus: 'healer' }),
  trinket({ id: 'permafrost-essence', itemId: 250244, name: 'Permafrost Essence', category: 'mythic-plus', instance: 'Den of Nalorakk', encounter: 'Sentinel of Winter', icon: 'inv12_jewelrytrinkets_dungeon_permafrostreservoir', type: 'passive', focus: 'tank' }),
  trinket({ id: 'war-loa-idol', itemId: 250229, name: 'Idol of the War Loa', category: 'mythic-plus', instance: 'Den of Nalorakk', encounter: 'Nalorakk', icon: 'inv12_jewelrytrinkets_dungeon_idolofthewargod', type: 'passive' }),
  trinket({ id: 'ruby-whelp-shell', itemId: 193757, name: 'Ruby Whelp Shell', category: 'mythic-plus', instance: 'Ruby Life Pools', encounter: 'Melidrussa Chillworn', icon: 'inv_item_dragonegg_redbroken01', type: 'on-use' }),
  trinket({ id: 'blazebinders-hoof', itemId: 193762, name: "Blazebinder's Hoof", category: 'mythic-plus', instance: 'Ruby Life Pools', encounter: 'Kokia Blazehoof', icon: 'inv_10_dungeonjewelry_primalist_trinket_2_fire', type: 'on-use', focus: 'strength' }),
  trinket({ id: 'kyrakka-embers', itemId: 193748, name: "Kyrakka's Searing Embers", category: 'mythic-plus', instance: 'Ruby Life Pools', encounter: 'Kyrakka', icon: 'inv_10_dungeonjewelry_primalist_trinket_4_fire', type: 'passive', focus: 'healer' }),
  trinket({ id: 'merekthas-fang', itemId: 158367, name: "Merektha's Fang", category: 'mythic-plus', instance: 'Temple of Sethraliss', encounter: 'Merektha', icon: 'inv_misc_food_87_sporelingsnack', type: 'on-use' }),
  trinket({ id: 'tiny-electromental', itemId: 158374, name: 'Tiny Electromental in a Jar', category: 'mythic-plus', instance: 'Temple of Sethraliss', encounter: 'Galvazzt', icon: 'inv_alchemy_71_potion4', type: 'passive' }),
  trinket({ id: 'sethraliss-relic', itemId: 158368, name: "Sethraliss' Defiled Relic", category: 'mythic-plus', instance: 'Temple of Sethraliss', encounter: 'Avatar of Sethraliss', icon: 'inv_staff_2h_snakeman_c_01', type: 'on-use' }),
  trinket({ id: 'golden-plumage', itemId: 159617, name: 'Lustrous Golden Plumage', category: 'mythic-plus', instance: "King's Rest", encounter: 'The Golden Serpent', icon: 'inv_icon_feather06a', type: 'on-use' }),
  trinket({ id: 'mchimba-bandages', itemId: 159618, name: "Mchimba's Ritual Bandages", category: 'mythic-plus', instance: "King's Rest", encounter: 'Mchimba the Embalmer', icon: 'inv_misc_emberweavebandagelight', type: 'on-use', focus: 'tank' }),
  trinket({ id: 'stormbound-emblem', itemId: 273649, name: 'Stormbound Emblem of Dazar', category: 'mythic-plus', instance: "King's Rest", encounter: 'King Dazar', icon: 'inv_7_0raid_necklace_14a', type: 'on-use' }),
];
